title: VRCFury
description: Non-Destructive Tools for VRChat Avatars
theme: just-the-docs
url: https://vrcfury.com
color_scheme: dark

nav_external_links:
  - title: Download
    url: https://vrcfury.com/download
  - title: Support Discord
    url: https://vrcfury.com/discord
  - title: Source Code
    url: https://github.com/VRCFury/VRCFury
